version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: task-manager-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
